### ISSUE TITLE
Buat halaman list kontributor

### ISSUE THREAD

**Issue by ardianta** [petanikode/belajar-git#137]
Data list kontributor dari repo ini bisa diambil dari:
- https://api.github.com/repos/petanikode/belajar-git/contributors

**Comment by nardiyansah** [comment]
permisi kak, mau nanya. halaman list kontributor yang dimaksud itu halaman statis ya ?

**Comment by ardianta** [comment]
> permisi kak, mau nanya. halaman list kontributor yang dimaksud itu halaman statis ya ?

Bisa, halaman HTML biasa taruh saja di folder `docs` biar bisa aktifkan github pages (#76 ). Datanya ambil dari link https://api.github.com/repos/petanikode/belajar-git/contributors dengan AJAX, bisa pakai `fetch()` API.

**Comment by ardianta** [comment]
Checkout the sandbox https://codesandbox.io/s/upbeat-snyder-btej8?fontsize=14&hidenavigation=1&theme=dark

**Comment by ardianta** [comment]
Terimakasih @nardiyansah, Github pages-nya sudah live di https://petanikode.github.io/belajar-git/index.html :tada:

**Comment by nardiyansah** [comment]
sama-sama kak

**Comment by heriprastiio** [comment]
Dapatkah saya berkontribusi untuk mengikuti event hacktoberfest menambahkan bahasa lain atau bagaimana? Saya tidak menemukan kontribusi pada file README.md pada repository ini?

**Comment by ardianta** [comment]
> Dapatkah saya berkontribusi untuk mengikuti event hacktoberfest menambahkan bahasa lain atau bagaimana? Saya tidak menemukan kontribusi pada file README.md pada repository ini?

Silahkan, repo ini terbuka buat pemula yang baru belajar tentang Git

**Comment by wawanneutron** [comment]
saya ikutan belajar ya bang , ikut contribusi

**Comment by yudanantoos** [comment]
Saya baca di web nya hindari menggunakan perintah "git add ." itu pengaruhnya apa ya kak?
Saya sudah fork dan sudah commit, nyoba perintah "git add ." gak ada yang aneh menurut saya.
Perubahan hanya 1 file kontribusi yang saya tambahkan,.
Mohon penjelasannya kak, saya mau ikut belajar dan berkontribusi di sini, terimakasih..

**Comment by ardianta** [comment]
> Saya baca di web nya hindari menggunakan perintah "git add ." itu pengaruhnya apa ya kak?
> Saya sudah fork dan sudah commit, nyoba perintah "git add ." gak ada yang aneh menurut saya.
> Perubahan hanya 1 file kontribusi yang saya tambahkan,.
> Mohon penjelasannya kak, saya mau ikut belajar dan berkontribusi di sini, terimakasih..

Tanda `.` buat memilih semua perubahan yang dilakukan. Nanti kalau udah kerja dengan banyak file, bisa merepotkan saat review kodenya.

**Comment by yudanantoos** [comment]
> > Saya baca di web nya hindari menggunakan perintah "git add ." itu pengaruhnya apa ya kak?
> > Saya sudah fork dan sudah commit, nyoba perintah "git add ." gak ada yang aneh menurut saya.
> > Perubahan hanya 1 file kontribusi yang saya tambahkan,.
> > Mohon penjelasannya kak, saya mau ikut belajar dan berkontribusi di sini, terimakasih..
> 
> Tanda `.` buat memilih semua perubahan yang dilakukan. Nanti kalau udah kerja dengan banyak file, bisa merepotkan saat review kodenya.

Oooo jd mksdnya 1 file, 1 add, 1 commit gtu ya, biar keliatan file mana dan apa saja yg dirubah,.
5 file yg dirubah, 5x add, dan 5x commit dengan pesan yg berbeda,.
Begitukah??

**Comment by ardianta** [comment]
> Oooo jd mksdnya 1 file, 1 add, 1 commit gtu ya, biar keliatan file mana dan apa saja yg dirubah,.
> 5 file yg dirubah, 5x add, dan 5x commit dengan pesan yg berbeda,.
> Begitukah??

Yap benar sekali.

Bisa juga memlilih dua file untuk satu commit, misal mau ubah layout.

File yang diubah:
- index.html
- style.css

Nanti tinggal di-add dan commit:

```bash
git add index.html style.css
git commit -m "fix: layout"
```

Tidak harus satu file satu commit

**Comment by yudanantoos** [comment]
> > Oooo jd mksdnya 1 file, 1 add, 1 commit gtu ya, biar keliatan file mana dan apa saja yg dirubah,.
> > 5 file yg dirubah, 5x add, dan 5x commit dengan pesan yg berbeda,.
> > Begitukah??
> 
> Yap benar sekali.
> 
> Bisa juga memlilih dua file untuk satu commit, misal mau ubah layout.
> 
> File yang diubah:
> 
> * index.html
> * style.css
> 
> Nanti tinggal di-add dan commit:
> 
> ```shell
> git add index.html style.css
> git commit -m "fix: layout"
> ```
> 
> Tidak harus satu file satu commit

Oo iya mantap terimakasih penjelasan nya kak, btw aku udh pull req kak, hehee
