### ISSUE TITLE
Aktifkan Github Pages untuk repository ini

### ISSUE THREAD

**Issue by hyuwah** [petanikode/belajar-git#76]
Halo admin Petanikode (mas @ardianta), 

Saya mau kasih ide/saran kalo repo ini diaktifkan fitur [github pages](https://www.petanikode.com/github-pages/) nya supaya kontributor / temen-temen yang belajar dan bikin file html di folder `kontributor` (maupun yang edit file html di root repo, `index.html`, `about.html`, dll) bisa juga lihat langsung hasilnya dalam bentuk website (mis. `https://petanikode.github.io/belajar-git/kontributor/[username-kontributor]`)

Harapannya sih biar bikin lebih _engaging_ buat yang belajar git nya gitu

Salam :pray:

**Comment by ardianta** [comment]
Terimakasih banyak atas sarannya, nanti saya perhitungkan lagi setelah merevisi tutorial Git di Petani Kode. :pray:
